condense_wildcard_suffixes=true
empty_item_single_line=false
enum_discrim_align_threshold=20
struct_field_align_threshold=20
fn_single_line=true
format_code_in_doc_comments=true

#format_generated_files=false

format_macro_matchers=true

#format_strings=true

hex_literal_case="Lower"
imports_indent="Visual"
#indent_style="Visual"
indent_style="Block"
merge_derives=true
imports_granularity="Module"
#reorder_impl_items=true
group_imports="StdExternalCrate"
#tab_spaces=2
use_field_init_shorthand=true
wrap_comments=true
