name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo deny
      run: cargo install cargo-deny
    - name: License check
      run: cargo deny check
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install fmt and clippy
      run: rustup component add rustfmt clippy
    - name: Fmt
      run: cargo fmt --check
    - name: Cargo check
      run: cargo check --all-targets
    - name: Clippy
      run: cargo clippy --all-targets
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Outdated check
      run: cargo outdated --exit-code 1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all-targets --verbose

